config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :users, only: [ :create, :new, :edit, :update ] do
    member do
      get "confirm_email"
      post "send_confirmation_email"
    end
  end
  resources :user_configs, only: [ :edit, :update ]

  root "workout_sessions#index"

  resources :workouts do
    collection do
      get "new_from_templates"
      post "create_from_templates"
    end

    member do
      patch "toggle_archived"
    end
  end

  resources :workout_sessions do
    member do
      post "duplicate"
    end
    resources :workout_instances, shallow: true, only: %i[new create destroy] do
      member do
        post "shift"
      end
      resources :workout_sets, shallow: true, only: %i[ new destroy create edit update ] do
        member do
          post "duplicate"
        end
      end
    end
  end

  get "/privacy", to: redirect("/privacy.html")

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :workout_instances, dependent: :destroy
  has_many :workout_sets, through: :workout_instances
  has_many :tag_registrations, dependent: :destroy
  has_many :tags, through: :tag_registrations

  validates :name, presence: true
  validates_size_of :name, within: 1..50

  validates :description, presence: true
  validates_size_of :description, within: 1..500

  validates :workout_type, presence: true
  validates_size_of :workout_type, within: 1..50

  validates :author, presence: true

  before_validation :check_uniqueness

  def highest_volume
    completed_workout_instances = workout_instances.filter { |workout_instance| workout_instance.workout_session.completed? }
    completed_workout_instances.max_by(&:volume)&.volume || 0
  end

  def unit
    author.user_config.get_unit workout_type
  end

  def check_uniqueness
    downcase = name.downcase
    user_workouts = Workout.where(author: author).where.not(id: self.id)
    user_workouts.each do |workout|
      if workout.name.downcase == downcase
        errors.add :name, "is already used in another workout"
      end
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  rate_limit to: 100, within: 1.minute
  before_action :get_workout, only: %i[ show edit update toggle_archived ]
  before_action :authorize_user, only: %i[ show edit update toggle_archived ]

  def index
    @archived = params[:archived].nil? ? false : params[:archived]
    @workouts = Current.user.workouts.where(archived: @archived).order("lower(name)")
    workout_names = @workouts.map { |workout| workout.name }
    @templates = WorkoutTemplates::WORKOUTS.each_with_index.select { |template, _| !workout_names.include? template[:name] }
  end

  def new
    @workout = Workout.new
  end

  def show
    @workout_instances = @workout.workout_instances.select { |instance| instance.workout_session.completed? }
    @workout_instances = @workout_instances.sort_by do | instance |
      instance.workout_session.date_completed
    end

    @workout_instances_desc = @workout_instances.reverse

    @labels = @workout_instances.map { | instance | instance.workout_session.date_completed }
    @data = @workout_instances.map { | instance | instance.volume }
    @highest_attempts = @workout_instances.map { | instance | instance.highest_attempt }
  end

  def edit
  end

  def toggle_archived
    @workout.archived = !@workout.archived
    @workout.save!
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "Successfully toggled archive status" }
    end
  end

  def update
    if params[:tag_ids].nil?
      flash.now[:alert] = "Must select tags (checkboxes) when editing a workout"
      render :new, status: :unprocessable_entity
      return
    end

    begin
      ActiveRecord::Base.transaction do
        @workout.update(workout_params)
        @workout.save!
        merge_tags_by_id(@workout, params[:tag_ids])
      end

      # TODO: might be worth making this go to the show path (i.e. workout_path(@workout))
      redirect_to workouts_path, notice: "Exercise successfully edited"
    rescue
      flash.now[:alert] = @workout.errors.full_messages.join("")
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @workout = Workout.new(workout_params)

    if params[:tag_ids].nil?
      flash.now[:alert] = "Must select tags (checkboxes) when creating a workout"
      render :new, status: :unprocessable_entity
      return
    end

    @workout.author = Current.user

    begin
      ActiveRecord::Base.transaction do
        @workout.save!
        add_tags_by_id(@workout, params[:tag_ids])
      end

      redirect_to workouts_path, notice: "Exercise successfully created"
    rescue ActiveRecord::RecordInvalid
      flash.now[:alert] = @workout.errors.full_messages.join("")
      render :new, status: :unprocessable_entity
    end
  end

  def new_from_templates
    workouts = Current.user.workouts.map { |workout| workout.name }
    @templates = WorkoutTemplates::WORKOUTS.each_with_index.select { |template, _| !workouts.include? template[:name] }
    if !@templates.any?
      redirect_to workouts_path, alert: "There are no more templates for you to add to your workouts."
    end
  end

  def create_from_templates
    template_indices = params[:template_indices]
    if template_indices.nil?
      flash.now[:alert] = "Please select a template to add."
      render_flash_stream(:unprocessable_entity)
      return
    end
    template_indices = template_indices.map &:to_i

    begin
      ActiveRecord::Base.transaction do
        create_workouts_with_tags_from_templates template_indices
        redirect_to workouts_path, notice: "Successfully created workouts from templates."
      end
    rescue ActiveRecord::RecordInvalid
      render new_from_templates, alert: "Could not create workouts from template."
    end
  end

  private

  def workout_params
    params.expect workout: [ :name, :description, :workout_type ]
  end

  def create_workouts_with_tags_from_templates(indices)
    indices.each do |index|
      template = WorkoutTemplates::WORKOUTS[index]
      workout = Workout.new

      build_workout_from_template workout, template
      add_tags_by_name workout, template[:tags]
    end
  end

  def build_workout_from_template(workout, template)
      workout.name = template[:name]
      workout.description = template[:description]
      workout.workout_type = template[:workout_type]
      workout.author = Current.user
      workout.save!
  end

  def merge_tags_by_id (workout, tag_ids)
    tag_registrations = workout.tag_registrations.includes(:tag, :workout)
    do_not_add = []

    workout.tags.all.each do |tag|
      tag_id_str = tag.id.to_s

      if !tag_ids.include? tag_id_str
        tag_registrations.find_by(tag_id: tag.id, workout_id: workout.id).destroy!
      else
        do_not_add.push(tag_id_str)
      end
    end

    tags_to_include = Tag.find(tag_ids).select { |tag| !do_not_add.include? tag.id.to_s }
    tags_to_include.each do |tag|
      add_tag_registration workout, tag
    end
  end

  def add_tags_by_id(workout, tag_ids)
    tags = Tag.find(tag_ids)
    tags.each do |tag|
      add_tag_registration workout, tag
    end
  end

  def add_tags_by_name(workout, tag_names)
    tags = tag_names.map { |title| Tag.find_by(title: title) }
    tags.each do |tag|
      add_tag_registration workout, tag
    end
  end

  def add_tag_registration(workout, tag)
    tag_registration = TagRegistration.new(workout: workout, tag: tag)
    tag_registration.save!
  end

  def authorize_user
    if @workout.author != Current.user
      redirect_to workout_sessions_path, alert: "You do not have permission to perform this action"
    end
  end

  def get_workout
    @workout = Workout.find(params[:id])
  end

  def check_for_tag_ids
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_with model: workout, class: "workout-form" do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, required: true, maxlength: 50, autofocus: true %>

  <%= form.label :description %>
  <%= form.text_area :description, required: true, maxlength: 500 %>

  <%= form.label :workout_type, "Workout Type" %>
  <%= form.select :workout_type, Constants::WORKOUT_TYPES %>

  <!-- TODO: This could potentially be optimized better but this will do -->
  <% workout_tags = workout.tags.all %>
  <% Tag.all.each do |tag| %>
    <div class="workout-checkbox-entry">
      <%= checkbox_tag "tag_ids[]", tag.id, workout_tags.include?(tag) %>
      <%= label_tag tag.title %>
    </div>
  <% end %>
 
  <%= form.submit class: "basic-button" %>
<% end %>

app/views/workouts/_template_form.html.erb
<h2>Select Templates</h2>
<%= form_with url: create_from_templates_workouts_path do |form| %>
  <% templates.each do |template| %>
    <div class="workout-checkbox-entry">
      <%= checkbox_tag "template_indices[]", template[1] %>
      <%= label_tag template[0][:name] %>
    </div>
  <% end %>

  <%= form.submit "Add Templates", class: "basic-button" %>
<% end %>

app/views/workouts/_workout.html.erb
<h1><%= workout.name %></h1>

<!-- TODO: make the divs reusable partials -->
<div
  data-controller="linechart"
  data-linechart-labels-value="<%= labels.to_json %>"
  data-linechart-numbers-value="<%= data.to_json %>"
  data-linechart-unit-value="<%= workout.unit %>"
  data-linechart-highest-attempts-value="<%= highest_attempts.to_json %>">
  <canvas id="line-chart" data-linechart-target="myChart" width="800" height="450"></canvas>
</div>

<div
  data-controller="highest-attempts-linechart"
  data-highest-attempts-linechart-labels-value="<%= labels.to_json %>"
  data-highest-attempts-linechart-unit-value="<%= workout.unit %>"
  data-highest-attempts-linechart-highest-attempts-value="<%= highest_attempts.to_json %>">
  <canvas id="highest-attempts-line-chart" data-highest-attempts-linechart-target="highestAttemptsChart" width="800" height="450"></canvas>
</div>

<table>
  <caption>History</caption>
  <thead>
    <tr>
      <th scope="col">Session</th>
      <th scope="col">Volume (<%= workout.unit %>)</th>
      <th scope="col">Highest Attempt (<%= workout.unit %>)</th>
      <th scope="col">Completed</th>
    </tr>
  </thead>
  <tbody>
    <% @workout_instances_desc.each do |workout_instance| %>
      <tr>
        <th scope="row"><%= link_to workout_instance.workout_session.title, workout_session_path(workout_instance.workout_session, anchor: dom_id(workout_instance)), data: { turbo: false } %></th>
        <td><%= workout_instance.volume %></td>
        <td><%= workout_instance.highest_attempt %></td>
        <td><%= workout_instance.workout_session.date_completed.strftime("%a, %b %-d %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workouts/_workout_card.html.erb
<div class="workout-card-top">
  <%= link_to workout.name, workout_path(workout)%>
</div>

<div class="workout-card-content">
  <span><%= workout.description %></span>
  <%= render "tags/tags", tags: workout.tags %>
</div>

<div class="workout-card-bottom">
  <%= link_to edit_workout_path(workout), class: "basic-card-button" do %>
    <%= render "icons/edit" %>
    <span>Edit</span>
  <% end %>

  <%= button_to toggle_archived_workout_path(workout), class: "cancel-button", method: :patch  do %>
    <%= render "icons/archive" %>
    <span>Archive</span>
  <% end %>
</div>

app/views/workouts/_workout_cards.html.erb
<div class="workouts">
  <% workouts.order(name: :asc).each do |workout| %>
    <div class="workout", id="<%= dom_id(workout) %>">
      <%= render "workouts/workout_card", workout: workout %>
    </div>
  <% end %>
</div>

app/views/workouts/_workouts.html.erb
<div class="workouts">
  <% workouts.order(name: :asc).each do |workout| %>
    <div class="workout">
      <%= render "workouts/workout", workout: workout %>
    </div>
  <% end %>
</div>

app/views/workouts/edit.html.erb
<%= render "workouts/form", workout: @workout %>

app/views/workouts/index.html.erb
<h1>
  <%= @archived ? render("icons/archive") : render("icons/barbell") %>
  My <%= "Archived " if @archived %>Exercises
</h1>

<% if !@archived %>
  <div class="new-workout-controls">
    <% if @templates.any? %>
      <%= link_to new_from_templates_workouts_path, class: "basic-button-full" do %>
        <%= render "icons/template" %>
        <span>Create From Template</span>
      <% end %>
    <% end %>


    <%= link_to new_workout_path, class: "basic-button-full" do %>
      <%= render "icons/plus" %>
      <span>Create Custom</span>
    <% end %>

    <%= link_to workouts_path(archived: true), class: "basic-button-full" do %>
      <%= render "icons/archive" %>
      <span>Show Archived</span>
    <% end %>
  </div>
  <% else %>
    <%= link_to workouts_path, class: "basic-button-full" do %>
      <%= render "icons/barbell" %>
      <span>Back to Exercises</span>
    <% end %>

<% end %>


<%= render "workouts/workout_cards", workouts: @workouts %>

app/views/workouts/new.html.erb
<%= render "workouts/form", workout: @workout %>

app/views/workouts/new_from_templates.html.erb
<h1>Exercise Templates</h1>
<p>This is the first step to setting up your exercises. Select from the fields below to add to your Exercises <%= render "icons/barbell" %> page.</p>
<p>All exercises on the Exercises <%= render "icons/barbell" %> page will then be used when you create sessions. Don't see a template here for an exercise you do? <%= link_to "Create your own exercise", new_workout_path %>.</p>
<p></p>
<%= render "workouts/template_form", templates: @templates %>

app/views/workouts/show.html.erb
<%= render "workouts/workout", workout: @workout, labels: @labels, data: @data, highest_attempts: @highest_attempts %>

app/views/workouts/toggle_archived.turbo_stream.erb
<%= turbo_stream.remove dom_id(@workout) %>