config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :users, only: [ :create, :new, :edit, :update ] do
    member do
      get "confirm_email"
      post "send_confirmation_email"
    end
  end
  resources :user_configs, only: [ :edit, :update ]

  root "workout_sessions#index"

  resources :workouts do
    collection do
      get "new_from_templates"
      post "create_from_templates"
    end

    member do
      patch "toggle_archived"
    end
  end

  resources :workout_sessions do
    member do
      post "duplicate"
    end
    resources :workout_instances, shallow: true, only: %i[new create destroy] do
      member do
        post "shift"
      end
      resources :workout_sets, shallow: true, only: %i[ new destroy create edit update ] do
        member do
          post "duplicate"
        end
      end
    end
  end

  get "/privacy", to: redirect("/privacy.html")

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :user
  has_many :workout_instances, dependent: :destroy
  has_many :workout_sets, through: :workout_instances
  validates :title, presence: true
  validates_size_of :title, within: 1..50
  validate :check_completion_validity
  validate :check_max_sessions, on: :create

  def completed?
    date_completed.present?
  end

  def ready_for_completion?
    if workout_instances.length == 0
      return false
    end

    workout_instances.each do |workout_instance|
      if workout_instance.workout_sets.length == 0
        return false
      end
    end

    true
  end

  def check_completion_validity
    if date_completed != nil && !ready_for_completion?
      errors.add :date_completed, "This workout session is not ready for completion."
    end
  end

  def check_max_sessions
    max = 10
    if user.workout_sessions.where(date_completed: nil).length >= max
      errors.add :base, "Max number of upcoming workout sessions reached. Max is #{max}"
    end
  end

  def deep_duplicate
    workout_session_dup = self.dup

    ActiveRecord::Base.transaction do
      workout_session_dup.date_completed = nil
      workout_session_dup.save!

      workout_instances.each do |workout_instance|
        workout_instance_dup = workout_instance.dup
        workout_instance_dup.workout = workout_instance.workout
        workout_instance_dup.workout_session = workout_session_dup
        workout_instance_dup.save!

        workout_instance.workout_sets.each do |workout_set|
          workout_set_dup = workout_set.dup
          workout_set_dup.workout_instance = workout_instance_dup
          workout_set_dup.save!
        end
      end
    end

    workout_session_dup
  end
end

app/controllers/workout_sessions_controller.rb
class WorkoutSessionsController < ApplicationController
  rate_limit to: 100, within: 1.minute
  before_action :get_workout_session, only: %i[show update destroy duplicate edit]
  before_action :authorize_user, only: %i[show update destroy duplicate]

  def index
    get_workout_sessions
  end

  def new
    @workout_session = WorkoutSession.new
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @workout_session.update(workout_session_params)
        format.turbo_stream
        format.html { redirect_to workout_sessions_path, notice: "Session updated!" }
      else
        flash.now[:alert] = "Failed to update workout session"
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end

  def create
    if !Current.user.workouts.any?
      redirect_to new_from_templates_workouts_path, alert: "You must have at least 1 workout to be able to make workout sessions."
      return
    end

    @workout_session = WorkoutSession.new(workout_session_params)
    @workout_session.user = Current.user

    respond_to do |format|
      if @workout_session.save
        format.turbo_stream
        format.html { redirect_to @workout_session, notice: "Session successfully created" }
      else
        flash.now[:alert] = @workout_session.errors.full_messages.join(", ")
        format.turbo_stream { render_flash_stream(:unprocessable_entity) }
        format.html do
          get_workout_sessions
          render :index, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @workout_session.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "Deletion successful" }
    end
  end

  def duplicate
    begin
      ActiveRecord::Base.transaction do
        @workout_session = @workout_session.deep_duplicate
      end
      respond_to do |format|
        format.turbo_stream
        format.html do
          get_workout_sessions
          render :index, notice: "Duplication Successful"
        end
      end
    rescue ActiveRecord::RecordInvalid => e
      flash.now[:alert] = e.record.errors.full_messages.join(", ")
      respond_to do |format|
        format.turbo_stream { render_flash_stream(:unprocessable_entity) }
        format.html do
          get_workout_sessions
          render :index, status: :unprocessable_entity
        end
      end
    end
  end

  private
  def get_workout_session
    @workout_session = WorkoutSession.find(params[:id])
  end

  def workout_session_params
    params.expect workout_session: [ :title, :date_completed ]
  end

  def get_workout_sessions
    today = Date.current
    @workout_sessions = Current.user.workout_sessions
    @upcoming_workout_sessions = @workout_sessions.where(date_completed: nil).order(created_at: :desc, updated_at: :desc)
    @completed_workout_sessions = @workout_sessions.where.not(date_completed: nil).order(date_completed: :desc, updated_at: :desc)
    @completed_sessions_this_week = @completed_workout_sessions.where(date_completed: today.beginning_of_week..today.end_of_week)
    @completed_sessions_last_week = @completed_workout_sessions.where(date_completed: today.beginning_of_week-7.days..today.end_of_week-7.days)
    @completed_sessions_long_ago = @completed_workout_sessions.where(date_completed: ..today.beginning_of_week-8.days)
  end

  def authorize_user
    if @workout_session.user != Current.user
      redirect_to workout_sessions_path, alert: "You do not have permission to perform this action"
    end
  end
end

app/helpers/workout_sessions_helper.rb
module WorkoutSessionsHelper
end

app/views/workout_sessions/_complete_workout_session.html.erb
<div class="complete-workout-session" id="<%= dom_id(workout_session, :complete) %>">
  <% if workout_session.completed? %>
    <p>Session completed on <%= workout_session.date_completed.in_time_zone(Current.user.time_zone).strftime("%a, %b %-d %Y") %></p>
  <% else %>
    <h2>Complete Session</h2>
    <% if workout_session.ready_for_completion? %>
      <%= render "workout_sessions/complete_workout_session_form", workout_session: workout_session %>
    <% else %>
      <p>This workout session is not ready for completion. Be sure to have at least 1 exercise in the session. All exercises must have at least one set.</p>
    <% end %>
  <% end %>
</div>

app/views/workout_sessions/_complete_workout_session_form.html.erb
<%= form_with model: workout_session do |form| %>
  <%= form.label :date_completed %>
  <%= form.date_select :date_completed, end_year: Date.today.year, start_year: 2000, selected: Date.today %>

  <%= form.button class: "green-button" do %>
    <%= render "icons/check" %>
    <span>Complete</span>
  <% end %>
<% end %>

app/views/workout_sessions/_form.html.erb
<%= turbo_frame_tag dom_id(workout_session, :title) do %>
  <%= form_with model: workout_session do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title, required: true, maxlength: 20, autofocus: true %>

    <%= form.button class: "green-button" do %>
        <span>Create</span>
      <%= render "icons/check" %>
    <% end %>
    <% if action == :new %>
      <%= link_to workout_sessions_path, class: "cancel-button" do %>
        <span>Cancel</span>
        <%= render "icons/x" %>
      <% end %>
    <% end %>

    <% if action == :edit %>
      <%= link_to workout_session_path(workout_session), class: "cancel-button" do %>
        <span>Cancel</span>
        <%= render "icons/x" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/workout_sessions/_new_workout_session_button.html.erb
<%= turbo_frame_tag dom_id(WorkoutSession.new, :title) do %>
  <%= link_to "New Session", new_workout_session_path, class: "basic-button" %>
<% end %>

app/views/workout_sessions/_session_card.html.erb
<div class="session-card" id="<%= dom_id(workout_session, :card) %>">
  <div class="session-card-top">
    <%= link_to workout_session_path(workout_session) do %> 
      <h1><%= workout_session.title %></h1>
      <%= render "icons/arrow_right" %>
    <% end %>
  </div>

  <ul class="session-card-workouts">
    <% workout_session.workout_instances.order(order_index: :asc).limit(5).each do |instance| %>
      <li>
        <%= instance.name %>
      </li>
    <% end %>

    <li>
      <% if workout_session.workout_instances.length > 5 %>
        ... and <%= workout_session.workout_instances.length - 5 %> more
      <% end %>
    </li>
  </ul>
  <div class="session-card-bottom">
    <%= button_to duplicate_workout_session_path(workout_session), method: :post, class: "basic-card-button" do %>
      <%= render "icons/duplicate" %>
    <% end %>
    <%= button_to workout_session_path(workout_session), method: :delete, class: "red-button" do %>
      <%= render "icons/delete" %>
    <% end %>
    <% if workout_session.completed? %>
      <% if workout_session.date_completed == Date.today %>
        <em style="color: var(--color-notice)">&#10003; Completed Today!</em>
      <% else %>
        <em>&#10003; <%= workout_session.date_completed.in_time_zone(Current.user.time_zone).strftime("%a, %b %-d %Y") %></em>
      <% end %>
    <% end %>
  </div>
</div>

app/views/workout_sessions/_session_cards.html.erb
<div class="session-cards" id="<%= group_id %>">
  <% workout_sessions.each do |workout_session| %>
    <%= render "workout_sessions/session_card", workout_session: workout_session %>
  <% end %>
</div>

app/views/workout_sessions/_title.html.erb
<header id="<%= dom_id(workout_session, :title_display) %>" class="session-title">
  <%= turbo_frame_tag dom_id(workout_session, :title) do %>
    <h1><%= workout_session.title %></h1>
    <%= link_to edit_workout_session_path(workout_session), class: "basic-button" do %>
      <%= render "icons/edit" %>
      <span>Edit</span>
    <% end %>
  <% end %>
</header>

app/views/workout_sessions/create.turbo_stream.erb
<%= turbo_stream.prepend "upcoming" do %>
  <%= render "workout_sessions/session_card", workout_session: @workout_session %>
<% end %>

<%= turbo_stream.replace dom_id(WorkoutSession.new, :title) do %>
  <%= render "workout_sessions/new_workout_session_button" %>
<% end %>

<%= turbo_stream.remove "no-sessions-notice" %>

app/views/workout_sessions/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@workout_session, :card) %>

app/views/workout_sessions/duplicate.turbo_stream.erb
<%= turbo_stream.prepend "upcoming" do %>
  <%= render "workout_sessions/session_card", workout_session: @workout_session %>
<% end %>

<%= turbo_stream.remove "no-sessions-notice" %>

app/views/workout_sessions/edit.html.erb
<%= render "workout_sessions/form", workout_session: @workout_session, action: :edit %>

app/views/workout_sessions/index.html.erb
<h1>Sessions</h1>
<% if Current.user.workouts.any? %>
  <%= render "workout_sessions/new_workout_session_button" %>
  <h2>Upcoming Sessions</h2>
  <% if !@upcoming_workout_sessions.any? %>
    <div id="no-sessions-notice">
      <p><em id="no-sessions-notice">You have no sessions coming up!</em></p>
      <p><em>Duplicate <%= render "icons/duplicate" %> an existing session or create a new one by selecting "New session" above.</em></p>
    </div>
  <% end %>
  <%= render "workout_sessions/session_cards", group_id: "upcoming", workout_sessions: @upcoming_workout_sessions %>
  <hr>
  <h2>Completed Sessions</h2>
  <h3>This week</h3>
  <%= render "workout_sessions/session_cards", group_id: "completed", workout_sessions: @completed_sessions_this_week %>
  <h3>Last week</h3>
  <%= render "workout_sessions/session_cards", group_id: "completed-last-week", workout_sessions: @completed_sessions_last_week %>
  <h3>2 weeks ago +</h3>
  <%= render "workout_sessions/session_cards", group_id: "completed-long-ago", workout_sessions: @completed_sessions_long_ago %>
<% else %>
  <p><em>You currently have no exercises. You'll need to create some exercises to use for your sessions! To get started, go to the <%= link_to "Exercises", workouts_path %> <%= render "icons/barbell" %> page</em></p>
<% end %>

app/views/workout_sessions/show.html.erb
<%= render "workout_sessions/workout_session", workout_session: @workout_session %>

app/views/workout_sessions/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@workout_session, :title_display) do %>
  <%= render "workout_sessions/title", workout_session: @workout_session %>
<% end %>

<%= turbo_stream.replace dom_id(@workout_session, :complete) do %>
  <%= render "workout_sessions/complete_workout_session", workout_session: @workout_session %>
<% end %>