config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :users, only: [ :create, :new, :edit, :update ] do
    member do
      get "confirm_email"
      post "send_confirmation_email"
    end
  end
  resources :user_configs, only: [ :edit, :update ]

  root "workout_sessions#index"

  resources :workouts do
    collection do
      get "new_from_templates"
      post "create_from_templates"
    end

    member do
      patch "toggle_archived"
    end
  end

  resources :workout_sessions do
    member do
      post "duplicate"
    end
    resources :workout_instances, shallow: true, only: %i[new create destroy] do
      member do
        post "shift"
      end
      resources :workout_sets, shallow: true, only: %i[ new destroy create edit update ] do
        member do
          post "duplicate"
        end
      end
    end
  end

  get "/privacy", to: redirect("/privacy.html")

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/workout_instance.rb
class WorkoutInstance < ApplicationRecord
  belongs_to :workout_session
  belongs_to :workout

  after_validation :send_to_order_bottom, on: :create
  has_many :workout_sets, dependent: :destroy
  validate :check_max_instances, on: :create

  def volume
    workout_sets.sum { |set| set.amount * set.reps }
  end

  def highest_attempt
    workout_sets.max_by(&:amount).amount
  end

  def name
    workout.name
  end

  def user
    workout_session.user
  end

  def check_max_instances
    max = 20
    if workout_session.workout_instances.length >= max
      errors.add :base, "Max number of workout sessions reached. Max is #{max}."
    end
  end

  def shift_order_up
    workout_instances = workout_session.workout_instances.order(:order_index)
    index = workout_instances.index self
    if index == 0
      return
    end

    if index == 1
      send_to_order_top
      return
    end

    previous_item = workout_instances[index - 1]
    previous_item_further = workout_instances[index - 2]

    self.order_index = (previous_item.order_index + previous_item_further.order_index) / 2
  end

  def shift_order_down
    workout_instances = workout_session.workout_instances.order(:order_index)
    index = workout_instances.index self

    if index == workout_instances.length - 1
      return
    end

    if index == workout_instances.length - 2
      send_to_order_bottom
      return
    end

    next_item = workout_instances[index + 1]
    following_item = workout_instances[index + 2]

    self.order_index = (next_item.order_index + following_item.order_index) / 2.0
  end

  def send_to_order_top
    workout_instances = workout_session.workout_instances.order(:order_index)
    index = workout_instances.index self
    if index == 0
      return
    end

    to_place_above = workout_session.workout_instances.order(:order_index).first
    self.order_index = (to_place_above.order_index / 2)
  end

  def send_to_order_bottom
    workout_instances = workout_session.workout_instances.order(:order_index)
    index = workout_instances.index self

    if workout_instances.length == 0
      self.order_index = 1.0
      return
    end

    if index == workout_instances.length - 1
      return
    end

    to_place_below = workout_session.workout_instances.order(:order_index).last
    self.order_index = (to_place_below.order_index + 1.0).floor
  end

  def self.dup_workout_sets(origin, receiver)
    sets = origin.workout_sets.map(&:dup)
    sets.each do |set|
      set.workout_instance = receiver
    end
    sets
  end

  def self.highest_volume (user, workout_instance)
    user_workout_instances = WorkoutInstance.where(workout: workout_instance.workout).select { |instance| instance.user == user }
    user_workout_instances.max { |a, b| a.volume <=> b.volume }
  end
end

app/controllers/workout_instances_controller.rb
class WorkoutInstancesController < ApplicationController
  rate_limit to: 100, within: 1.minute
  before_action :get_workout_session, only: %i[ new create ]
  before_action :authorize_user, only: %i[create]

  def new
    @workout_instance = WorkoutInstance.new
    @workouts = Current.user.workouts.where(archived: false).order(name: :asc)
  end

  def create
    @workout_instance = @workout_session.workout_instances.new(workout_instance_params)

    begin
      ActiveRecord::Base.transaction do
        @workout_instance.save!
        best_workout_instance = WorkoutInstance.highest_volume(Current.user, @workout_instance)
        workout_sets = WorkoutInstance.dup_workout_sets(best_workout_instance, @workout_instance)
        workout_sets.each(&:save!)

        respond_to do |format|
          format.turbo_stream
          format.html { redirect_to @workout_session, notice: "Workout instance created" }
        end
      rescue ActiveRecord::RecordInvalid => e
        flash.now[:alert] = e.record.errors.full_messages.join(", ")
        respond_to do |format|
          format.turbo_stream { render_flash_stream(:unprocessable_entity) }
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @workout_instance = WorkoutInstance.find(params[:id])
    @workout_instance.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "Successfully deleted workout instance" }
    end
  end

  def shift
    @workout_instance = WorkoutInstance.find(params[:id])
    @workout_session = @workout_instance.workout_session
    shift_direction = params[:shift_direction]

    case shift_direction
    when "top"
      @workout_instance.send_to_order_top
    when "bottom"
      @workout_instance.send_to_order_bottom
    when "up"
      @workout_instance.shift_order_up
    when "down"
      @workout_instance.shift_order_down
    end

    if @workout_instance.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to root_path, alert: @workout_instance.errors.full_messages.join(", ")
    end
  end

  private
  def get_workout_session
    @workout_session = WorkoutSession.find(params[:workout_session_id])
  end

  def workout_instance_params
    params.expect workout_instance: [ :workout_id ]
  end

  def authorize_user
    if Current.user != @workout_session.user
      redirect_to workout_sessions_path, alert: "You do not have permission to perform this action"
    end
  end

  def save_workout_session_with_sets
  end
end

app/helpers/workout_instances_helper.rb
module WorkoutInstancesHelper
end

app/views/workout_instances/_form.html.erb
<%= turbo_frame_tag combined_dom_id(workout_session, WorkoutInstance.new), class: "new-workout-instance" do %>
  <%= form_with model: [workout_session, workout_instance] do |form| %>
    <%= form.label :workout_id, "Exercise" %>
    <%= form.collection_select :workout_id, workouts, :id, :name %>

    <%= form.button class: "green-button" do %>
      <%= render "icons/check" %>
    <% end %>
    <%= link_to workout_session_path(workout_session), class: "cancel-button" do %>
      <%= render "icons/x" %>
    <% end %>
  <% end %>
<% end %>

app/views/workout_instances/_new_workout_instance_button.html.erb
<%= turbo_frame_tag combined_dom_id(workout_session, WorkoutInstance.new), class: "new-workout-instance" do %>
  <%= link_to "Add Exercise", new_workout_session_workout_instance_path(workout_session), class: "basic-button" %>
<% end %>

app/views/workout_instances/_workout_instance.html.erb
<% completed = workout_instance.workout_session.completed? %>
<div class="workout-instance" id="<%= dom_id(workout_instance) %>">
  <div class="workout-instance-title">
    <%= link_to workout_instance.workout.name, workout_path(workout_instance.workout) %>
    <% if !completed %>
      <%= button_to workout_instance_path(workout_instance), method: :delete, class: "red-button" do %>
        <%= render "icons/delete" %>
        <span>Delete</span>
      <% end %>
    <% end %>
  </div>

  <%= render "workout_sets/workout_sets", workout_instance: workout_instance %>

  <div class="workout-instance-controls">
    <% if !completed %>
      <%= render "workout_sets/new_workout_set_button", workout_instance: workout_instance %>
    <% end %>

  </div>
    <% if !completed %>
      <div class="shift-instance-controls">
        <%= button_to shift_workout_instance_path(workout_instance), method: :post, class: "basic-card-button", params: { shift_direction: "up" } do %>
          <%= render "icons/arrow_up" %>
        <% end %>
        <%= button_to shift_workout_instance_path(workout_instance), method: :post, class: "basic-card-button", params: { shift_direction: "down" } do %>
          <%= render "icons/arrow_down" %>
        <% end %>
        <%= button_to shift_workout_instance_path(workout_instance), method: :post, class: "basic-card-button", params: { shift_direction: "top" } do %>
          <%= render "icons/arrow_to_top" %>
        <% end %>
        <%= button_to shift_workout_instance_path(workout_instance), method: :post, class: "basic-card-button", params: { shift_direction: "bottom" } do %>
          <%= render "icons/arrow_to_bottom" %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/workout_instances/_workout_instances.html.erb
<% workout_instances.each do |workout_instance| %>
  <%= render "workout_instances/workout_instance", workout_instance: workout_instance, workout_session: workout_instance.workout_session %>
<% end %>

app/views/workout_instances/create.turbo_stream.erb
<%= turbo_stream.append dom_id(@workout_instance.workout_session, :workouts) do %>
  <%= render "workout_instances/workout_instance", workout_instance: @workout_instance, workout_session: @workout_instance.workout_session %>
<% end %>

<%= turbo_stream.replace combined_dom_id(@workout_instance.workout_session, WorkoutInstance.new) do %>
  <%= render "workout_instances/new_workout_instance_button", workout_session: @workout_instance.workout_session %>
<% end %>

<%= turbo_stream.replace dom_id(@workout_instance.workout_session, :complete) do %>
  <%= render "workout_sessions/complete_workout_session", workout_session: @workout_instance.workout_session %>
<% end %>

app/views/workout_instances/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@workout_instance) %>
<%= turbo_stream.replace dom_id(@workout_instance.workout_session, :complete) do %>
  <%= render "workout_sessions/complete_workout_session", workout_session: @workout_instance.workout_session %>
<% end %>

app/views/workout_instances/new.html.erb
<%= render "workout_instances/form", workout_instance: @workout_instance, workout_session: @workout_session, workouts: @workouts %>

app/views/workout_instances/shift.turbo_stream.erb
<%= turbo_stream.replace dom_id(@workout_session, :workouts) do %>
  <div class="workout-instances" id="<%= dom_id(@workout_session, :workouts) %>">
    <%= render "workout_instances/workout_instances", workout_instances: @workout_session.workout_instances.order(order_index: :asc) %>
  </div>
<% end %>