config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :users, only: [ :create, :new, :edit, :update ] do
    member do
      get "confirm_email"
      post "send_confirmation_email"
    end
  end
  resources :user_configs, only: [ :edit, :update ]

  root "workout_sessions#index"

  resources :workouts do
    collection do
      get "new_from_templates"
      post "create_from_templates"
    end

    member do
      patch "toggle_archived"
    end
  end

  resources :workout_sessions do
    member do
      post "duplicate"
    end
    resources :workout_instances, shallow: true, only: %i[new create destroy] do
      member do
        post "shift"
      end
      resources :workout_sets, shallow: true, only: %i[ new destroy create edit update ] do
        member do
          post "duplicate"
        end
      end
    end
  end

  get "/privacy", to: redirect("/privacy.html")

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flash.html.erb
<div id="flash">
  <% flash.each do |type, message| %>
    <%= tag.div(message, style: "color:red", role: "alert", data: { controller: "flash" }) if type == "alert" %>
    <%= tag.div(message, style: "color:var(--color-notice)", role: "alert") if type == "notice" %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <ul>
    <% if authenticated? %>
      <li>
        <%= link_to root_path, class: "basic-button" do %>
          <%= render "icons/home" %>
          <span>Sessions</span>
        <% end %>
      </li>
      <li>
        <%= link_to workouts_path, class: "basic-button" do %>
          <%= render "icons/barbell" %>
          <span>Exercises</span>
        <% end %>
      </li>
      <li class="nav-elem-right">
        <%= link_to edit_user_path(Current.user), class: "basic-button" do %>
          <%= render "icons/user" %>
          <span>Account</span>
        <% end %>
      </li>
      <li>
        <%= link_to edit_user_config_path(Current.user.user_config), class: "basic-button" do %>
          <%= render "icons/settings" %>
          <span>Settings</span>
        <% end %>
      </li>
      <li>
        <%= button_to session_path, method: :delete do %>
          <%= render "icons/logout" %>
          <span>Log out</span>
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to new_session_path, class: "text-only-button" do %>
          <span>Log in</span>
        <% end %>
      </li>
      <li>
        <%= link_to new_user_path, class: "text-only-button" do %>
          <span>Register</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sesh" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag 'favicon.ico' %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    <div class="content">
      <%= yield %>
      <hr>
      <footer>
        <%= link_to "Privacy Policy", privacy_path %>
        <a href="https://tabler.io/icons">Icons from tabler.io</a>
        <p>&copy; 2025 Daniel Febles</p>
      </footer>
    </div>
  </body>
</html>